# Generated by Django 6.0.6 on 2026-06-26 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_id', models.CharField(blank=True, max_length=64)),
                ('company_name', models.CharField(max_length=160)),
                ('company_logo', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16)),
                ('work_type', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='onsite', max_length=16)),
                ('schedule_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('freelance', 'Freelance'), ('contract', 'Contract')], default='full-time', max_length=16)),
                ('schedule_pattern', models.CharField(choices=[('standard', 'Standard'), ('flexible-hours', 'Flexible hours'), ('weekends', 'Weekends'), ('night-shift', 'Night shift')], default='standard', max_length=16)),
                ('location_label', models.CharField(max_length=160)),
                ('location_city', models.CharField(blank=True, max_length=120)),
                ('location_country', models.CharField(blank=True, default='Uzbekistan', max_length=120)),
                ('location_is_remote', models.BooleanField(default=False)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('salary_min', models.PositiveIntegerField(default=0)),
                ('salary_max', models.PositiveIntegerField(default=0)),
                ('salary_currency', models.CharField(default='USD', max_length=8)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.category')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['is_featured'], name='jobs_job_is_feat_3f31c0_idx'), models.Index(fields=['category'], name='jobs_job_categor_24d294_idx'), models.Index(fields=['work_type'], name='jobs_job_work_ty_4ebff2_idx'), models.Index(fields=['location_lat', 'location_lng'], name='jobs_job_locatio_4b565d_idx'), models.Index(fields=['-created_at'], name='jobs_job_created_77460a_idx')],
            },
        ),
    ]
